name: Release Artifacts

on:
  push:
    branches: [ "develop", "main" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  container_images:
    name: Build Container Images
    strategy:
      matrix:
        arch: [amd64, arm64]
        runner: [self-hosted, ubuntu-latest]
        exclude:
        - arch: amd64
          runner: self-hosted
        - arch: arm64
          runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
    - id: metadata
      name: Configure Container Metadata
      uses: docker/metadata-action@v4
      with:
        flavor:
          suffix=-${{ matrix.arch }}
        images: |
          ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
          type=sha
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major.minor}}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
    - name: Install OverlayFS
      if: ${{ matrix.arch == 'arm64' }}
      run: |
        apt-get install -y fuse-overlayfs skopeo
    - name: Build Container
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: linux/${{ matrix.arch }}
        extra-args: |
          --isolation=chroot
        containerfiles: |
          ./Containerfile
    - name: Log in to Registry
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - name: Push to Registry (arm64)
      if: ${{ matrix.arch == 'arm64' }}
      run: |
        skopeo copy containers-storage:${{ steps.build_image.outputs.image-with-tag }} ${{ env.IMAGE_REGISTRY }}/${{ steps.build_image.outputs.image-with-tag }}
    - name: Push to Registry (amd64)
      if: ${{ matrix.arch != 'arm64' }}
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}

  multiarch_image:
    name: Multi-Arch Container Image
    needs: container_images
    runs-on: ubuntu-latest
    steps:
    - name: Install Buildah and Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y buildah podman
    - id: metadata
      name: Configure Container Metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
          type=sha
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major.minor}},priority=850
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }},825
    - name: Tag Container
      env:
        IMAGE_ID: ${{ fromJSON(steps.metadata.outputs.json).tags[0] }}
        ALL_TAGS: ${{ join(fromJSON(steps.metadata.outputs.json).tags, ' ')}}
      run: |
        buildah manifest create ${{ env.IMAGE_NAME }}
        buildah manifest add ${{ env.IMAGE_NAME }} ${{ env.IMAGE_ID }}-amd64
        buildah manifest add ${{ env.IMAGE_NAME }} ${{ env.IMAGE_ID }}-arm64
        buildah tag ${{ env.IMAGE_NAME }} ${{ env.ALL_TAGS }}
    - name: Push to Registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ steps.metadata.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

